### ISSUE TITLE
Eliminar comentarios

### ISSUE THREAD

**Issue by Nidev-lab** [zeta-dev-web/stock-back#1]
Buenas! como va? encontre algunos comentarios en el codigo,

![image](https://github.com/zeta-dev-web/stock-back/assets/53904695/42700126-e224-460c-8501-3609674d7927)

Recuerden, los comentarios no estan vistos como una buena practica , pero en si el codigo comentado es mucho menos aceptado.

Cualquier cosita podes contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by MVillalbaZ** [comment]
Se eliminan Comentarios Adicionales del Codigo.

Commits de referencia en rama main:
735068c 7a9f5c2
